OPTIONS_MAX:
  data_csv: data/Geopotential_selected_max.csv
  es_max: true
  lat_range:
  - 25
  - 90
  levels: 70
  lon_range:
  - -180
  - 180
  time: 0
OPTIONS_MIN:
  data_csv: data/Geopotential_selected_min.csv
  es_max: false
  lat_range:
  - 25
  - 90
  levels: 70
  lon_range:
  - -180
  - 180
  time: 0
